/**
 * Bibliothèque de bâtiments-types — pré-remplissages d'audit pour
 * accélérer la saisie. Chaque template couvre les ~30 champs les plus
 * impactants. L'utilisateur ajuste ensuite.
 */

export interface BatimentType {
  id: string;
  nom: string;
  description: string;
  /** Synthèse des chiffres clés affichée sur la carte. */
  highlights: string[];
  /** DPE estimé pour rapide repérage visuel. */
  dpeEstime: string;
  values: Record<string, string>;
}

export const BATIMENTS_TYPES: BatimentType[] = [
  {
    id: "maison-1970-non-renovee",
    nom: "Maison T5 années 70 — non rénovée",
    description: "Pavillon brique 120 m² zone H1, simple vitrage, chaudière fioul vétuste.",
    highlights: ["120 m²", "Zone H1c", "Chaudière fioul 1980"],
    dpeEstime: "F",
    values: {
      type_batiment: "Maison individuelle",
      annee_construction: "1972",
      surface_habitable: "120",
      surface_plancher: "135",
      nb_niveaux: "2",
      hauteur_plafond: "2.5",
      zone_climatique: "H1c — Est",
      orientation: "Sud",
      mitoyennete: "Isolé (4 façades)",
      type_structure: "Brique",
      murs_composition: "Brique pleine 30 cm — sans isolant",
      murs_isolation: "Non isolé",
      toiture_composition: "Tuiles + combles perdus non isolés",
      toiture_isolation: "Non isolé",
      plancher_composition: "Dalle béton sur terre-plein",
      plancher_isolation: "Non isolé",
      menuiseries_type: "Simple vitrage bois",
      surface_vitree_totale: "18",
      chauffage_type: "Chaudière fioul",
      chauffage_annee: "1985",
      chauffage_rendement: "65",
      ecs_type: "Cumulus électrique",
      ventilation_type: "Naturelle",
      conso_par_m2: "380",
      emissions_co2_m2: "85",
    },
  },
  {
    id: "maison-1970-renovee",
    nom: "Maison T5 années 70 — rénovée années 2010",
    description: "Pavillon 120 m² avec ITE, double vitrage récent et PAC air/eau.",
    highlights: ["120 m²", "ITE R=4", "PAC air/eau"],
    dpeEstime: "C",
    values: {
      type_batiment: "Maison individuelle",
      annee_construction: "1972",
      surface_habitable: "120",
      surface_plancher: "135",
      nb_niveaux: "2",
      hauteur_plafond: "2.5",
      zone_climatique: "H1c — Est",
      orientation: "Sud",
      mitoyennete: "Isolé (4 façades)",
      type_structure: "Brique",
      murs_composition: "Brique 30 cm + ITE PSE 14 cm (2015)",
      murs_isolation: "Isolation extérieure (ITE)",
      murs_r: "4",
      toiture_composition: "Combles perdus + laine soufflée R=7",
      toiture_isolation: "Bien isolé (R ≥ 6)",
      toiture_r: "7",
      plancher_composition: "Dalle béton + isolant sous-face R=2.5",
      plancher_isolation: "Isolé en sous-face",
      plancher_r: "2.5",
      menuiseries_type: "Double vitrage récent",
      surface_vitree_totale: "20",
      chauffage_type: "PAC air/eau",
      chauffage_annee: "2017",
      chauffage_rendement: "300",
      ecs_type: "PAC air/eau",
      ventilation_type: "VMC simple flux hygro B",
      conso_par_m2: "120",
      emissions_co2_m2: "12",
    },
  },
  {
    id: "appartement-1990-bien-isole",
    nom: "Appartement T3 années 90",
    description: "65 m² en immeuble collectif béton, double vitrage, chauffage gaz collectif.",
    highlights: ["65 m²", "Zone H2b", "Gaz collectif"],
    dpeEstime: "D",
    values: {
      type_batiment: "Appartement",
      annee_construction: "1992",
      surface_habitable: "65",
      surface_plancher: "70",
      nb_niveaux: "1",
      hauteur_plafond: "2.5",
      zone_climatique: "H2b — Ouest",
      orientation: "Sud",
      mitoyennete: "Mitoyen deux côtés",
      type_structure: "Béton",
      murs_composition: "Voile béton + doublage PSE 8 cm",
      murs_isolation: "Isolation intérieure",
      murs_r: "2.5",
      toiture_composition: "Plancher haut entre étages",
      toiture_isolation: "Correctement isolé (R 4-6)",
      plancher_isolation: "Correctement isolé",
      menuiseries_type: "Double vitrage récent",
      surface_vitree_totale: "9",
      chauffage_type: "Chaudière gaz collective",
      chauffage_annee: "1992",
      chauffage_rendement: "75",
      ecs_type: "Chaudière gaz collective",
      ventilation_type: "VMC simple flux autoréglable",
      conso_par_m2: "180",
      emissions_co2_m2: "32",
    },
  },
  {
    id: "bureau-1990-non-renove",
    nom: "Bureau tertiaire années 90 — non rénové",
    description: "Plateau 800 m² ossature béton, simple flux, chauffage gaz, climatisation DRV.",
    highlights: ["800 m²", "Tertiaire", "DEET applicable"],
    dpeEstime: "E",
    values: {
      type_batiment: "Bâtiment tertiaire",
      usage_batiment: "Bureaux",
      annee_construction: "1995",
      surface_habitable: "800",
      surface_plancher: "850",
      nb_niveaux: "2",
      hauteur_plafond: "2.7",
      zone_climatique: "H1c — Est",
      orientation: "Sud",
      mitoyennete: "Isolé (4 façades)",
      type_structure: "Béton",
      murs_composition: "Béton + doublage PSE 6 cm",
      murs_isolation: "Isolation intérieure",
      toiture_composition: "Toiture terrasse + isolant 8 cm",
      toiture_isolation: "Insuffisamment isolé (< R 4)",
      plancher_isolation: "Non isolé",
      menuiseries_type: "Double vitrage ancien (avant 2000)",
      surface_vitree_totale: "180",
      chauffage_type: "Chaudière gaz",
      chauffage_annee: "1995",
      chauffage_rendement: "70",
      ecs_type: "Cumulus électrique",
      ventilation_type: "VMC simple flux autoréglable",
      conso_par_m2: "230",
      emissions_co2_m2: "45",
    },
  },
  {
    id: "ecole-2010",
    nom: "Groupe scolaire RT2005",
    description: "École 1500 m², ossature béton, double vitrage performant, chaudière condensation.",
    highlights: ["1500 m²", "Public", "Condensation"],
    dpeEstime: "C",
    values: {
      type_batiment: "Bâtiment public",
      usage_batiment: "Autre",
      annee_construction: "2010",
      surface_habitable: "1500",
      surface_plancher: "1600",
      nb_niveaux: "2",
      hauteur_plafond: "3.0",
      zone_climatique: "H2a — Nord-Ouest",
      orientation: "Sud-Est",
      mitoyennete: "Isolé (4 façades)",
      type_structure: "Béton",
      murs_composition: "Béton + ITE laine de roche 12 cm",
      murs_isolation: "Isolation extérieure (ITE)",
      murs_r: "3.5",
      toiture_composition: "Toiture terrasse étanchéité + PUR R=5",
      toiture_isolation: "Correctement isolé (R 4-6)",
      toiture_r: "5",
      plancher_isolation: "Isolé sous dalle",
      menuiseries_type: "Double vitrage récent",
      surface_vitree_totale: "260",
      chauffage_type: "Chaudière gaz condensation",
      chauffage_annee: "2010",
      chauffage_rendement: "95",
      ecs_type: "Chaudière gaz condensation",
      ventilation_type: "VMC double flux",
      conso_par_m2: "130",
      emissions_co2_m2: "22",
    },
  },
  {
    id: "commerce-2000",
    nom: "Commerce de détail années 2000",
    description: "Local commercial 250 m², parpaing, simple flux, climatisation split, éclairage LED partiel.",
    highlights: ["250 m²", "Commerce", "Split"],
    dpeEstime: "D",
    values: {
      type_batiment: "Bâtiment tertiaire",
      usage_batiment: "Commerce",
      annee_construction: "2002",
      surface_habitable: "250",
      surface_plancher: "260",
      nb_niveaux: "1",
      hauteur_plafond: "3.5",
      zone_climatique: "H3 — Méditerranée",
      orientation: "Sud",
      mitoyennete: "Mitoyen deux côtés",
      type_structure: "Parpaing",
      murs_composition: "Parpaing 20 cm + doublage PSE 6 cm",
      murs_isolation: "Isolation intérieure",
      murs_r: "1.8",
      toiture_composition: "Bac acier + laine R=3",
      toiture_isolation: "Insuffisamment isolé (< R 4)",
      toiture_r: "3",
      plancher_isolation: "Non isolé",
      menuiseries_type: "Double vitrage ancien (avant 2000)",
      surface_vitree_totale: "45",
      chauffage_type: "Climatisation réversible (split)",
      chauffage_annee: "2005",
      chauffage_rendement: "280",
      ecs_type: "Cumulus électrique",
      ventilation_type: "VMC simple flux autoréglable",
      conso_par_m2: "200",
      emissions_co2_m2: "28",
    },
  },
];
